
package pl.agh.soa.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DaysToHolidays", targetNamespace = "http://webservice.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DaysToHolidays {


    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "oneDayMore", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.OneDayMore")
    @ResponseWrapper(localName = "oneDayMoreResponse", targetNamespace = "http://webservice.soa.agh.pl/", className = "pl.agh.soa.webservice.OneDayMoreResponse")
    @Action(input = "http://webservice.soa.agh.pl/DaysToHolidays/oneDayMoreRequest", output = "http://webservice.soa.agh.pl/DaysToHolidays/oneDayMoreResponse", fault = {
        @FaultAction(className = ParseException_Exception.class, value = "http://webservice.soa.agh.pl/DaysToHolidays/oneDayMore/Fault/ParseException")
    })
    public String oneDayMore()
        throws ParseException_Exception
    ;

}
