
package pl.agh.soa.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaysToHolidaysImplService", targetNamespace = "http://webservice.soa.agh.pl/", wsdlLocation = "http://localhost:8080/days/ToHolidays?wsdl")
public class DaysToHolidaysImplService
    extends Service
{

    private final static URL DAYSTOHOLIDAYSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAYSTOHOLIDAYSIMPLSERVICE_EXCEPTION;
    private final static QName DAYSTOHOLIDAYSIMPLSERVICE_QNAME = new QName("http://webservice.soa.agh.pl/", "DaysToHolidaysImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/days/ToHolidays?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAYSTOHOLIDAYSIMPLSERVICE_WSDL_LOCATION = url;
        DAYSTOHOLIDAYSIMPLSERVICE_EXCEPTION = e;
    }

    public DaysToHolidaysImplService() {
        super(__getWsdlLocation(), DAYSTOHOLIDAYSIMPLSERVICE_QNAME);
    }

    public DaysToHolidaysImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAYSTOHOLIDAYSIMPLSERVICE_QNAME, features);
    }

    public DaysToHolidaysImplService(URL wsdlLocation) {
        super(wsdlLocation, DAYSTOHOLIDAYSIMPLSERVICE_QNAME);
    }

    public DaysToHolidaysImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAYSTOHOLIDAYSIMPLSERVICE_QNAME, features);
    }

    public DaysToHolidaysImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaysToHolidaysImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaysToHolidays
     */
    @WebEndpoint(name = "DaysToHolidaysImplPort")
    public DaysToHolidays getDaysToHolidaysImplPort() {
        return super.getPort(new QName("http://webservice.soa.agh.pl/", "DaysToHolidaysImplPort"), DaysToHolidays.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaysToHolidays
     */
    @WebEndpoint(name = "DaysToHolidaysImplPort")
    public DaysToHolidays getDaysToHolidaysImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.soa.agh.pl/", "DaysToHolidaysImplPort"), DaysToHolidays.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAYSTOHOLIDAYSIMPLSERVICE_EXCEPTION!= null) {
            throw DAYSTOHOLIDAYSIMPLSERVICE_EXCEPTION;
        }
        return DAYSTOHOLIDAYSIMPLSERVICE_WSDL_LOCATION;
    }

}
